#!/bin/bash
###################################################################
#Programmer: Isaac Kerley
#Updated date: 10/6/17
#############################Main##################################
cd /etc/yum.repos.d/                                              #Goes to the yum folder
wget http://wing-net.ddo.jp/wing/7/EL7.wing.repo                  #Downloads wing repo
sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/EL7.wing.repo   #Installs wing
yum clean all                                                     #Cleans up yum

