#!/bin/bash
echo installing samba 4 AD
python which-distro.py
distro=$(cat distro.txt)
if [ "centos" = "$distro" ]
then
    bash ./CentOS/install-ad
elif [ "ubuntu" = "$distro" ]
then
    bash ./Ubuntu/install-ad
    
elif [ "fedora" = "$distro" ]
then
    bash ./Fedora/install-ad
elif [ "debian" = "$distro" ]
then
    bash ./Debian/install-ad

fi
