#!/bin/bash
yum install epel-release -y
yum install vim -y
yum install wget -y 
yum install authconfig -y 
yum install krb5-workstation -y
yum install samba45 -y
yum install samba45-winbind-clients -y
yum install samba45-winbind samba45-client -y
yum install samba45-dc -y
yum install samba45-pidl -y 
yum install samba45-python -y
yum install samba45-winbind-krb5-locator -y
yum install perl-Parse-Yapp -y 
yum install perl-Test-Base -y
yum install python2-crypto 
yum install samba45-common-tools -y 
bash install-wing-repo
