#!/bin/bash
echo installing samba 4 AD
python which-distro.py
distro=$(cat distro.txt)
if [ "centos" = "$distro" ]
then
    yum install epel-release -y
    yum install vim -y
    yum install wget -y 
    yum install authconfig -y 
    yum install krb5-workstation -y
    yum install samba45 -y
    yum install samba45-winbind-clients -y
    yum install samba45-winbind samba45-client -y
    yum install samba45-dc -y
    yum install samba45-pidl -y 
    yum install samba45-python -y
    yum install samba45-winbind-krb5-locator -y
    yum install perl-Parse-Yapp -y 
    yum install perl-Test-Base -y
    yum install python2-crypto -y
    yum install samba45-common-tools -y
elif [ "ubuntu" = "$distro" ]
then
    apt-get install -y update
    apt-get install -y samba
    apt-getinstall -y krb5-user
    apt-getinstall -y krb5-config
    apt-getinstall -y winbind
    apt-getinstall -y libpam-winbind
    apt-getinstall -y libnss-winbind
elif [ "fedora" = "$distro" ]
then
    dnf install vim -y
    dnf install wget -y 
    dnf install authconfig -y 
    dnf install krb5-workstation -y
    dnf install samba45 -y
    dnf install samba45-winbind-clients -y
    dnf install samba45-winbind samba45-client -y
    dnf install samba45-dc -y
    dnf install samba45-pidl -y 
    dnf install samba45-python -y
    dnf install samba45-winbind-krb5-locator -y
    dnf install perl-Parse-Yapp -y 
    dnf install perl-Test-Base -y
    dnf install python2-crypto -y
    dnf install samba45-common-tools -y
elif [ "debian" = "$distro" ]
then
    bash ./Debian/install-ad

fi
