#!/bin/bash
######################################
#Programmer: Isaac Kerley
#Updated date: 10/6/17
###############Main###################
mv /etc/samba/smb.conf /etc/samba/smb.conf.initial
samba-tool domain provision --use-rfc2307 --interactive
samba-tool domain level show
