#!/bin/bash
echo installing for fedora packages
#dnf install epel-release -y
dnf install vim -y
dnf install wget -y 
dnf install authconfig -y 
dnf install krb5-workstation -y
dnf install samba45 -y
dnf install samba45-winbind-clients -y
dnf install samba45-winbind samba45-client -y
dnf install samba45-dc -y
dnf install samba45-pidl -y 
dnf install samba45-python -y
dnf install samba45-winbind-krb5-locator -y
dnf install perl-Parse-Yapp -y 
dnf install perl-Test-Base -y
dnf install python2-crypto -y
dnf install samba45-common-tools -y

